# Override for running with authentication enabled.
# Usage: docker compose -f docker-compose.dev.yaml -f docker-compose.auth.yaml up -d --build
services:
  pushkinlib:
    environment:
      - AUTH_ENABLED=true
